pull_request_rules:
  - name: backport patches to checkpoint/0-setup-boilerplate
    conditions:
      - base=main
      - label=backport/checkpoint/0-setup-boilerplate
    actions:
      backport:
        branches:
          - checkpoint/0-setup-boilerplate
  - name: backport patches to checkpoint/1-instantiate-msg-stubs
    conditions:
      - base=main
      - label=backport/checkpoint/1-instantiate-msg-stubs
    actions:
      backport:
        branches:
          - checkpoint/1-instantiate-msg-stubs